const WORD_SETS = [
  {
    english: "Hello",
    thai: "sa-wadt dee cúp",
    audioIndex: 1,
    gender: "man",
    note: "",
  },
  {
    english: "Hello",
    thai: "sa-wadt dee káa",
    audioIndex: 2,
    gender: "woman",
    note: "",
  },
  {
    english: "How are you?",
    thai: "sa-bai dee mái cúp?",
    audioIndex: 3,
    gender: "man",
    note: "",
  },
  {
    english: "How are you?",
    thai: "sa-bai dee mái kâa?",
    audioIndex: 4,
    gender: "woman",
    note: "",
  },
  {
    english: "What is your name?",
    thai: "khun chûu a-rai cúp?",
    audioIndex: 5,
    gender: "man",
    note: "",
  },
  {
    english: "What is your name?",
    thai: "khun chûu a-rai kâa?",
    audioIndex: 6,
    gender: "woman",
    note: "",
  },
  {
    english: "My name is...",
    thai: "phǒm chûu Robert",
    audioIndex: 7,
    gender: "man",
    note: "",
  },
  {
    english: "My name is...",
    thai: "di-chan chûu Lonna",
    audioIndex: 8,
    gender: "woman",
    note: "",
  },
  {
    english: "Thank you",
    thai: "khop khun cúp",
    audioIndex: 9,
    gender: "man",
    note: "",
  },
  {
    english: "Thank you",
    thai: "khop khun káa",
    audioIndex: 10,
    gender: "woman",
    note: "",
  },
  {
    english: "You're welcome",
    thai: "yin dee cúp",
    audioIndex: 11,
    gender: "man",
    note: "",
  },
  {
    english: "You're welcome",
    thai: "yin dee káa",
    audioIndex: 12,
    gender: "woman",
    note: "",
  },
  {
    english: "Can (instead of yes)",
    thai: "dâi cúp",
    audioIndex: 13,
    gender: "man",
    note: "",
  },
  {
    english: "Can (instad of yes)",
    thai: "dâi káa",
    audioIndex: 14,
    gender: "woman",
    note: "",
  },
  {
    english: "Cannot (instead of no)",
    thai: "mâi dâi cúp",
    audioIndex: 15,
    gender: "man",
    note: "",
  },
  {
    english: "Cannot (instead of no)",
    thai: "mâi dâi káa",
    audioIndex: 16,
    gender: "woman",
    note: "",
  },
  {
    english: "Want (instead of yes)",
    thai: "àow cúp",
    audioIndex: 17,
    gender: "man",
    note: "",
  },
  {
    english: "Want (instead of yes)",
    thai: "àow káa",
    audioIndex: 18,
    gender: "woman",
    note: "",
  },
  {
    english: "Don't want (instead of no)",
    thai: "mâi àow cúp",
    audioIndex: 19,
    gender: "man",
    note: "",
  },
  {
    english: "Don't want (instead of no)",
    thai: "mâi àow káa",
    audioIndex: 20,
    gender: "woman",
    note: "",
  },
  {
    english: "Let's pray",
    thai: "a-thí-taan gòne",
    audioIndex: 21,
    gender: "man",
    note: "",
  },
  {
    english: "Let's pray",
    thai: "a-thí-taan gòne",
    audioIndex: 22,
    gender: "woman",
    note: "",
  },
  {
    english: "Be healed in Jesus name",
    thai: "??",
    audioIndex: 23,
    gender: "man",
    note: "",
  },
  {
    english: "Be healed in Jesus name",
    thai: "??",
    audioIndex: 24,
    gender: "woman",
    note: "",
  },
  {
    english: "Jesus loves you",
    thai: "phrá yay-suu rák khun",
    audioIndex: 25,
    gender: "man",
    note: "",
  },
  {
    english: "Jesus loves you",
    thai: "phrá yay-suu rák khun",
    audioIndex: 26,
    gender: "woman",
    note: "",
  },
  {
    english: "God bless you",
    thai: "phrá jâo ow-way pǒn cúp",
    audioIndex: 27,
    gender: "man",
    note: "",
  },
  {
    english: "God bless you",
    thai: "phrá jâo ow-way pǒn káa",
    audioIndex: 28,
    gender: "woman",
    note: "",
  },
];
