const WORD_SETS = [
  {
  english: "Hello",
  thai: "สวัสดีครับ",
  audioIndex: 1,
  gender: "man",
},
{
  english: "Hello",
  thai: "สวัสดีค่ะ",
  audioIndex: 2,
  gender: "woman",
},
{
  english: "How are you?",
  thai: "สบายดีไหมครับ",
  audioIndex: 3,
  gender: "man",
},
{
  english: "How are you?",
  thai: "สบายดีไหมคะ",
  audioIndex: 4,
  gender: "woman",
},
{
  english: "What is your name?",
  thai: "คุณชื่ออะไรครับ",
  audioIndex: 5,
  gender: "man",
},
{
  english: "What is your name?",
  thai: "คุณชื่ออะไรคะ",
  audioIndex: 6,
  gender: "woman",
},
{
  english: "My name is...",
  thai: "ผมชื่อ...",
  audioIndex: 7,
  gender: "man",
},
{
  english: "My name is...",
  thai: "ฉันชื่อ...",
  audioIndex: 8,
  gender: "woman",
},
{
  english: "Thank you",
  thai: "ขอบคุณครับ",
  audioIndex: 9,
  gender: "man",
},
{
  english: "Thank you",
  thai: "ขอบคุณค่ะ",
  audioIndex: 10,
  gender: "woman",
},
{
  english: "You're welcome",
  thai: "ยินดีครับ",
  audioIndex: 11,
  gender: "man",
},
{
  english: "You're welcome",
  thai: "ยินดีค่ะ",
  audioIndex: 12,
  gender: "woman",
},
{
  english: "Can",
  thai: "ได้ครับ",
  audioIndex: 13,
  gender: "man",
},
{
  english: "Can",
  thai: "ได้ค่ะ",
  audioIndex: 14,
  gender: "woman",
},
{
  english: "Cannot",
  thai: "ไม่ได้ครับ",
  audioIndex: 15,
  gender: "man",
},
{
  english: "Cannot",
  thai: "ไม่ได้ค่ะ",
  audioIndex: 16,
  gender: "woman",
},
{
  english: "Want",
  thai: "อยากครับ",
  audioIndex: 17,
  gender: "man",
},
{
  english: "Want",
  thai: "อยากค่ะ",
  audioIndex: 18,
  gender: "woman",
},
{
  english: "Don't want",
  thai: "ไม่อยากครับ",
  audioIndex: 19,
  gender: "man",
},
{
  english: "Don't want",
  thai: "ไม่อยากค่ะ",
  audioIndex: 20,
  gender: "woman",
},
{
  english: "Let's pray",
  thai: "มาอธิษฐานกันครับ",
  audioIndex: 21,
  gender: "man",
},
{
  english: "Let's pray",
  thai: "มาอธิษฐานกันค่ะ",
  audioIndex: 22,
  gender: "woman",
},
{
  english: "Be healed in Jesus name",
  thai: "ขอให้หายในพระนามพระเยซูครับ",
  audioIndex: 23,
  gender: "man",
},
{
  english: "Be healed in Jesus name",
  thai: "ขอให้หายในพระนามพระเยซูค่ะ",
  audioIndex: 24,
  gender: "woman",
},
{
  english: "God loves you",
  thai: "พระเจ้าทรงรักคุณครับ",
  audioIndex: 25,
  gender: "man",
},
{
  english: "God loves you",
  thai: "พระเจ้าทรงรักคุณค่ะ",
  audioIndex: 26,
  gender: "woman",
},
{
  english: "Jesus loves you",
  thai: "พระเยซูทรงรักคุณครับ",
  audioIndex: 27,
  gender: "man",
},
{
  english: "Jesus loves you",
  thai: "พระเยซูทรงรักคุณค่ะ",
  audioIndex: 28,
  gender: "woman",
},
{
  english: "God bless you",
  thai: "ขอพระเจ้าอวยพรคุณครับ",
  audioIndex: 29,
  gender: "man",
},
{
  english: "God bless you",
  thai: "ขอพระเจ้าอวยพรคุณค่ะ",
  audioIndex: 30,
  gender: "woman",
},
];
